#!/bin/bash

cachedir="$HOME/.cache/l7-dmenu-desktop"
configdir="$HOME/.config/l7-dmenu-desktop"
lockfile="$cachedir/lock"
aliasescache="$cachedir/dmenu_aliases"
aliasesnamecache="$cachedir/dmenu_aliases_names"
aliasesfile="$configdir/aliases"

checkrunning()
{
    [ ! -e "$1" ] && mkdir -p "$1"
    if [[ -f "$2" ]]
    then
        echo "Already running!"
        exit 1
    else
        touch "$2"
    fi
}

get_alias_name()
{
    if [[ $1 = "alias "*"="* ]]
    then
        echo "${1//alias /}" | awk -F "=" '{print $1}'
    fi
}

update_alias()
{
	if [[ -f "$3" ]]
	then
		if [[ ! -f "$1" || ! -f "$2" ]]
		then
			[[ -f "$2" ]] && rm "$2"
			cp -f "$3" "$1"
            readarray -t aliases < "$1"
            for alias in "${aliases[@]}"
            do
                get_alias_name "$alias" >> "$2"
            done
		elif ! diff -q "$1" "$3" >/dev/null 2>&1
		then
			readarray -t changes < <(diff "$1" "$3")
			for change in "${changes[@]}"
			do
				if [[ "$change" = ">"* ]]
				then
					alias="${change//> /}"
					get_alias_name "$alias" >> "$2"
				elif [[ "$change" = "<"* ]]
				then
					alias="${change//< /}"
					sed -i "/$(get_alias_name "$alias")/d" "$2"
				fi
			done
            cp -f "$3" "$1"
		fi
		cat "$2"
	fi
}

checkrunning "$cachedir" "$lockfile"
update_alias "$aliasescache" "$aliasesnamecache" "$aliasesfile"
rm "$lockfile"