#!/bin/bash

if [[ $1 = "--help" || $1 = "-h" ]]
then
    printf '%s\n' "Use --dmenu=<menu> to change menu command" \
                "When not using --dmenu= flag arguments are passed to regular dmenu"
    exit 0
fi

cachedir="$HOME/.cache/l7-dmenu-desktop"
configdir="$HOME/.config/l7-dmenu-desktop"
lockfile_aliases="$cachedir/lock_aliases"
lockfile_desktop="$cachedir/lock_desktop"
aliasesfile="$configdir/aliases"
addpath="$configdir/addpath"
excludefile="$configdir/excludes"
filecaches=(
	"$cachedir/files_global"
	"$cachedir/files_global_local"
	"$cachedir/files_local"
	"$cachedir/files_flatpak_global"
	"$cachedir/files_flatpak_local"
)
namecaches=(
    "$cachedir/names_global"
    "$cachedir/names_global_local"
    "$cachedir/names_local"
    "$cachedir/names_flatpak_global"
    "$cachedir/names_flatpak_local"
)

checkrunning()
{
    if [[ -f "$1" || -f "$2" ]]
    then
        echo "Already running!" >&2
        exit 1
    fi
}

execute()
{
    if [[ -n $1 ]]
    then
        if [[ -f "$aliasesfile" ]] && grep -q "^alias $1=" "$aliasesfile"
        then
            eval "$(sed "s/^alias $1=//g" "$aliasesfile")"
        else
            for namecache in "${namecaches[@]}"
            do
                if [[ -f "$namecache" ]] && grep -q "^$1;" "$namecache"
                then
                    dex --term alacritty "$(grep "^$1;" "$namecache" | awk -F "; " '{print $2}' | awk NR==1)" &
                    return
                fi
            done
            command "$1"
        fi
    fi
}

exclude()
{
    list="$2"
    if [[ -f "$1" ]]
    then
        readarray -t excludes < "$1"
        for exclude in "${excludes[@]}"
        do
            list=$(sed "/^$exclude$/d" <(echo "${list[@]}"))
        done
    fi
    echo "${list[@]}"
}

info()
{
    for i in "${!filecaches[@]}"
    do
        if [[ -f "${filecaches[$i]}" ]]
       then
            read=$((read + $(wc -l < "${filecaches[$i]}")))
        fi
        if [[ -f "${namecaches[$i]}" ]]
        then
            found=$((found + $(wc -l < "${namecaches[$i]}")))
        fi
    done
    echo "Read $read .desktop files, found $found apps."
}

checkrunning "$lockfile_aliases" "$lockfile_desktop"
echo -ne "looking for changes..." && \
if [[ -f "$addpath" ]]
then
    entries=$(exclude "$excludefile" "$( (dmenu_desktop & dmenu_aliases & dmenu_path) 2>/dev/null | sort -u )")
else
    entries=$(exclude "$excludefile" "$( (dmenu_desktop & dmenu_aliases) 2>/dev/null | sort -u )")
fi && \
echo -ne "\r\033[K"
info &
if [[ $1 = "--dmenu="* ]]
then
    menu=${1//--dmenu=/}
else
    menu="dmenu $*"
fi
selection=$(echo "${entries[@]}" | $menu)
execute "$selection"